name: Release Create

on:
  push:
    tags:
      - v*

jobs:
  release-create:
    uses: apecloud/apecloud-cd/.github/workflows/release-create.yml@v0.1.34
    with:
      APECD_REF: "v0.1.34"
    secrets: inherit
